### ISSUE TITLE
unity ios symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by ghus86** [Azure/azure-spatial-anchors-samples#27]
Hi 

I have downloaded the sample from here and added the arkit assets folder 
but when I make the build I get an error saying symbol(s) not found for architecture arm64

In the quick steps you mention to run the  .xcworkspace file instead of the .xcodeproj file 
but that file isnt in the folder

also having issues in running pod install --repo-update (doesnt recognized the command but cocoapods is installed) is there some alternative to this step

@craigktreasure @vriveras any idea ?
thanks in advance

ps: I was able to run the android sample and work with it and I am using Unity 2018.3.6

part of the error below

`_NativeLibrary_ssc_session_error_event_args_release_mEDED3848D389420B7B852D2AC25A7CC40F024592 in Bulk_Assembly-CSharp_0.o\
      _SessionErrorEventArgs_Finalize_mC79DDF754A677DF097334E4DFE9206861475B448 in Bulk_Assembly-CSharp_0.o\
     (maybe you meant: _NativeLibrary_ssc_session_error_event_args_release_mEDED3848D389420B7B852D2AC25A7CC40F024592)\
  "_ssc_cloud_spatial_anchor_session_diagnostics_addref", referenced from:\
      _CloudSpatialAnchorSessionDiagnostics__ctor_mFF7CBDA6CE41A20A974739C52DFCD149DFC108F2 in Bulk_Assembly-CSharp_0.o\
      _NativeLibrary_ssc_cloud_spatial_anchor_session_diagnostics_addref_m9E5CDBB05E4ACEC9D4445D0A855A0F5BDD54F092 in Bulk_Assembly-CSharp_0.o\
     (maybe you meant: _NativeLibrary_ssc_cloud_spatial_anchor_session_diagnostics_addref_m9E5CDBB05E4ACEC9D4445D0A855A0F5BDD54F092)\
ld: symbol(s) not found for architecture arm64\
clang: error: linker command failed with exit code 1 (use -v to see invocation)}`

**Comment by craigktreasure** [comment]
You'll need to get the `pod install --repo-update` command (documented [here](https://guides.cocoapods.org/terminal/commands.html#pod_install)) working as that command creates the `.xcworkspace` file. I suspect that there's something up with your installation of the CocoaPods client. See [here](https://guides.cocoapods.org/using/getting-started.html).

**Comment by ghus86** [comment]
Thanks that solved my issue

**Comment by MichealReed** [comment]
@craigktreasure do you have any insight into what ASA does when generating the .xcworkspace file with `pod install --repo-update'? I need to use a parent project's workspace since I am using unity as a library. I am facing the same issue with symbols not found.

**Comment by MichealReed** [comment]
@craigktreasure could you please elaborate on what the ASA pod install does to generate the `.xcworkspace`? I need to use a parent workspace to build my project and after trying several things, I'm still having difficulties getting the ASA apis to link.

**Comment by vriveras** [comment]
@MichealReed , ASA doesn't do anything related to the .xcworkspace this is standard process when you use a POD in the XCode project. When you add a pod a new workspace is created that adds the pod dependencies to it. You can see the details [here](https://guides.cocoapods.org/using/using-cocoapods.html#what-is-happening-behind-the-scenes)

**Comment by MichealReed** [comment]
@vriveras I may be running into a different issue then. I thought it might be related to the copy resources step from your link. I'm on 2019.3.0f5 and upgraded my podfile as mentioned here: https://github.com/Azure/azure-spatial-anchors-samples/issues/79

Getting the same "undefined symbol" errors.

**Comment by MichealReed** [comment]
Solved, had a version mismatch in the podfile.

**Comment by oyvind-soroy** [comment]
Now what?

> quakeulf@Jan-Eivind-sin-MacBook-Pro anchers % pod install --repo-update
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.

[!] The Podfile does not contain any dependencies.
